### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Resonanz** [newfla/egui-theme-switcher#6]
Curious... why Apache rather than MIT?

**Comment by newfla** [comment]
I think it is a more comprehensive license, and I have always been comfortable with it.
If you find it problematic to use in other software, it is not a big problem for me to switch to the MIT.

**Comment by Resonanz** [comment]
I think many people won't use code that is not MIT licensed since it bring complications with it. Personally, I like your widget but the license doesn't work for me. Thanks your your kind reply.

**Comment by newfla** [comment]
@Resonanz v0.1.2 released under MIT license
